# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/Learning/LearningCpp/WordCount/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/Learning/LearningCpp/WordCount/cmake_build/CMakeFiles/3.29.0/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/Learning/LearningCpp/WordCount/cmake_build/CMakeFiles/3.29.0/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/Learning/LearningCpp/WordCount/cmake_build/CMakeFiles/3.29.0/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/Apple-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/Apple-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/Apple-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/Apple-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/share/cmake-3.29/Modules/Platform/UnixPaths.cmake))

/Users/j1012505/Data/Learning/LearningCpp/WordCount/cmake_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Users/j1012505/Data/TransportPlanner/Softwares/lib/python3.11/site-packages/cmake/data/bin/cmake -S/Users/j1012505/Data/Learning/LearningCpp/WordCount -B/Users/j1012505/Data/Learning/LearningCpp/WordCount/cmake_build
